### ISSUE TITLE
Have Travis run tests

### ISSUE THREAD

**Issue by Varunram** [nwutils/Web2Executable#203]
It would be nice if we could add Travis to run the tests so that we can get a green tick with every PR, making sure that its safe to merge.

**Comment by jyapayne** [comment]
I agree. I've just uploaded the travis yaml file and hopefully, that will trigger the travis build. However, the tests are not really in a good state. I started writing tests retroactively at one point but ended up not having enough time to complete them, so they aren't indicative of any sort of stability right now.

**Comment by Varunram** [comment]
Ah, not a worry, I'll see what we can do there. Thanks!
