### ISSUE TITLE
Request to move repo under NW Userland

### ISSUE THREAD

**Issue by ayushmxn** [nwutils/Web2Executable#210]
Hi @jyapayne,

I'm part of a GitHub org called [NW Utils](https://github.com/nwutils). I'm trying to consolidate NW tooling so it's easier to find useful projects and give much needed life to stagnant ones. I also think this would be a great opportunity to exchange ideas and learn new things. Let me know what you think and if you’d be willing to.

Best Regards
Ayushman

**Comment by TheJaredWilcurt** [comment]
Either way, this project has been a part of the NW.js landscape for a long time. I remember playing around with it when I was just learning Node-Webkit. Invited you to be a member anyway @jyapayne.

**Comment by jyapayne** [comment]
Thanks! I meant to contact you, but I just didn't have time. I think your consolidation idea is good. I'll transfer over the repo.

**Comment by TheJaredWilcurt** [comment]
Cool, I set you as admin, should be back to normal
